### ISSUE TITLE
Botones sin acción en el footer

### ISSUE THREAD

**Issue by Nidev-lab** [Herra2113/codePET-Front#13]
## Proceso

1. Ingrese a la pagina.
2. Baje hasta el footer.

## Resultado esperado

• Que los botones redirijan a dicho lugar o redirijan a un 404.

## Resultado actual

• Los botones no redirigen ni cumplen ninguna acción.  

## Captura

![image](https://github.com/Herra2113/codePET-Front/assets/53904695/0fe149d1-9f89-411f-9e4d-2d325f93b1aa)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Buenas Carlos! Tendrías las credenciales de admin para pasarme? Ya que las enviadas son invalidas.

**Comment by Herra2113** [comment]
Hola cómo estás?
Las credenciales de admin son
User: ***@***.***
Pasa: Admin123!

**Comment by Herra2113** [comment]
Solucionado el problema de redireccion de los botones del footer
