### ISSUE TITLE
Errores de consola

### ISSUE THREAD

**Issue by Nidev-lab** [Herra2113/codePET-Front#14]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• No encontrar errores de consola.

## Resultado actual

• Se encuentran errores de consola.

## Captura

![image](https://github.com/Herra2113/codePET-Front/assets/53904695/f97723ea-35fc-4dce-a365-81f89e365904)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Herra2113** [comment]
Al ingresar en la pagina, ya no se visualizan errores en la consola.
