### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Nidev-lab** [Herra2113/codePET-Front#15]
## Proceso

1. Ingrese a la pagina.
2. Me quise loguear con un usuario admin.

## Resultado esperado

• Poder ingresar sin problema alguno.

## Resultado actual

• No se puede ingresar y genera errores en consola.

## Captura

![image](https://github.com/Herra2113/codePET-Front/assets/53904695/bbff02aa-e311-4538-99a4-6e9aa9386c66)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Herra2113** [comment]
Ya se puede logear como admin en la pagina
Las credenciales son las mismas que envie por mail.
Por alguna razon el primer deploy del front que hice no estaba conectado con el back.
Tuve que deployear de nuevo el front para poder solucionar el problema.
El link es el siguiente: [codepet.netlify.app](https://codepet.netlify.app/)
