### ISSUE TITLE
Form nuevo paciente

### ISSUE THREAD

**Issue by Nidev-lab** [Herra2113/codePET-Front#19]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario admin.
3. Quise crear nuevos pacientes.

## Resultado esperado

• Que no se permitan colocar numero ni signos en los nombres.

## Resultado actual

• Se permiten colocar numeros y signos.

## Captura

![image](https://github.com/Herra2113/codePET-Front/assets/53904695/3a10e3e1-4002-4185-9fe6-aae6d0dccf6c)
![image](https://github.com/Herra2113/codePET-Front/assets/53904695/d45933d6-70a8-4194-8cb7-9440ca6c7cd3)
![image](https://github.com/Herra2113/codePET-Front/assets/53904695/64d0b565-654f-49c4-aacb-5b7fc47f82a0)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Herra2113** [comment]
Se agregaron validaciones a los formularios.
