### ISSUE TITLE
Turnos

### ISSUE THREAD

**Issue by Nidev-lab** [Herra2113/codePET-Front#20]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario admin.
3. Quise registrar nuevos turnos.

## Resultado esperado

• Que al darle a guardar los turnos queden registrados.

## Resultado actual

• Al darle a guardar el modal se cierra y los turnos no quedan registrados.

## Captura

![image](https://github.com/Herra2113/codePET-Front/assets/53904695/9ac5a5f7-bfe3-47ee-90fe-378ce4d0a22f)
![image](https://github.com/Herra2113/codePET-Front/assets/53904695/861c70ff-bc1f-4be1-9e79-dbc275ed433b)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Herra2113** [comment]
Ya se puede crear turnos correctamente.
